name: todo

services:
    
  api:
    container_name: todo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - ConnectionStrings__ToDoConnectionString=Server=db;Database=${DB_NAME:?DB_NAME environment variable is missing};User Id=${DB_USER:?DB_USER environment variable is missing};Password=${MSSQL_SA_PASSWORD:?MSSQL_SA_PASSWORD environment variable is missing};Encrypt=true;TrustServerCertificate=true;
      - EmailSettings__Host=${EmailSettings__Host:?EmailSettings__Host is missing}
      - EmailSettings__Port=${EmailSettings__Port:?EmailSettings__Port is missing}
      - EmailSettings__From=${EmailSettings__From:?EmailSettings__From is missing}
      - EmailSettings__UserName=${EmailSettings__UserName:?EmailSettings__UserName is missing}
      - EmailSettings__Password=${EmailSettings__Password:?EmailSettings__Password is missing}
      - Jwt__Audience=${Jwt__Audience:?Jwt__Audience environment variable is missing}
      - Jwt__Issuer=${Jwt__Issuer:?Jwt__Issuer environment variable is missing}
      - Jwt__Expiration=${Jwt__Expiration:?Jwt__Expiration environment variable is missing}
      - Jwt__Key=${Jwt__Key:?Jwt__Key environment variable is missing}
    depends_on:
      db:
        restart: true
        condition: service_started
        required: true
    networks:
      - default
      - backend

  db:
    container_name: todo-db
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:?MSSQL_SA_PASSWORD environment variable is missing}
    shm_size: 1g
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - backend

volumes:
  db-data:
    name: todo-db-data

networks:
  default:
    name: todo-default
    driver: bridge
  backend:
    name: todo-backend
    driver: bridge
    internal: true