name: todo

services:
    
  api:
    container_name: todo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__ToDoConnectionString=Server=db;Database=${DB_NAME:?DB_NAME environment variable is missing};User Id=${DB_USER:?DB_USER environment variable is missing};Password=${MSSQL_SA_PASSWORD:?MSSQL_SA_PASSWORD environment variable is missing};Encrypt=true;TrustServerCertificate=true;
      - EmailSettings__Email=${EmailSettings__Email:?EmailSettings__Email is missing}
      - EmailSettings__Password=${EmailSettings__Password:?EmailSettings__Password is missing}
      - Jwt__Audience=${Jwt__Audience:?Jwt__Audience environment variable is missing}
      - Jwt__Issuer=${Jwt__Issuer:?Jwt__Issuer environment variable is missing}
      - Jwt__Expiration=${Jwt__Expiration:?Jwt__Expiration environment variable is missing}
      - Jwt__Key=${Jwt__Key:?Jwt__Key environment variable is missing}
    depends_on:
      db:
        restart: true
        condition: service_started
        required: true

  db:
    container_name: todo-db
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:?MSSQL_SA_PASSWORD environment variable is missing}
    ports:
      - "1434:1433"
    shm_size: 1g
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
    name: todo-db-data